import Head from 'next/head';
import Image from 'next/image';
import Swiper from '../components/swiper';
import style from '../styles/Home.module.scss';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Fashion App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link rel="preconnect" href="https://fonts.gstatic.com" />
				<link
					href="https://fonts.googleapis.com/css2?family=Cinzel&family=Italiana&display=swap"
					rel="stylesheet"
				></link>
			</Head>
			<div className={style.appContainer}>
				<div className={style.mainContainer}>
					<h1 className="title">Street Style</h1>
				</div>
				<Swiper />
			</div>
		</div>
	);
}
